// <auto-generated />
namespace CMSSample.DA.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Initial_Migration_15062021 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initial_Migration_15062021));
        
        string IMigrationMetadata.Id
        {
            get { return "202106150724539_Initial_Migration_15062021"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
